
import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Chau',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin:  true,
        },
        {
            name: 'Mi',
            email: 'user@example.com',
            password: bcrypt.hashSync('5678', 8),
            isAdmin:  false,
        },
    ],
    products:[
        {
            name:'Samsung Galaxy Z Flip3 5G',
            category: 'Phone',
            image:'/image/download-1.jpg',
            price: 1200,
            countInStock : 10,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name:'Iphone 7',
            category: 'Phone',
            image:'/image/download.jpg',
            price: 799,
            countInStock: 0,
            brand: 'Iphone',
            rating: 4.0,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name:'Chanel Boy',
            category: 'Bags',
            image:'/image/download-3.jpg',
            price: 4999,
            countInStock: 8,
            brand: 'Chanel',
            rating: 4.8,
            numReviews: 20,
            description:'high quality product',
        },
        {
            name:'Chanel Classic',
            category: 'Bags',
            image:'/image/download-2.jpg',
            price: 6299,
            countInStock: 4,
            brand: 'Chanel',
            rating: 4.7,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name:'Chanel Boy Mini',
            category: 'Bags',
            image:'/image/download-5.jpg',
            price: 3999,
            countInStock: 8,
            brand: 'Chanel',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name:'Chanel',
            category: 'Bags',
            image:'/image/download-4.jpg',
            price: 4999,
            countInStock: 9,
            brand: 'Chanel',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/image/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/image/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/image/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/image/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/image/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/image/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ]
};

export default data;

